### ISSUE TITLE
There are some errors in the dataset

### ISSUE THREAD

**Issue by a849173140** [ryo-ma/covid19-japan-web-api#29]
First of all, thank you very much for your contribution to the fight against COVID. I found some errors when using this data

1 Total and Total history have different Numbers of deaths

2 Total history's number of PCR on 2020-03-19 and 2020-03-25, Because the number of these two days is less than the previous two days.

**Comment by ryo-ma** [comment]
Thank you for your issue.
I will research the problem.

**Comment by swsoyee** [comment]
Hi, I'm not the author of this repository, but the data are collected by myself (https://github.com/swsoyee/2019-ncov-japan), so maybe I can answer your question.

> 1. Total and Total history have different Numbers of deaths

In fact, I haven't read the source code of this repository, and I can't figure out how the author @ryo-ma calculate the death,

In this (https://covid19-japan-web-api.now.sh/api/v1/total?history=true) json response:
```
  {
    "date": 20200508,
    "pcr": 169546,
    "positive": 16338,
    "symptom": 9224,
    "symptomless": 1024,
    "symptomConfirming": 5134,
    "hospitalize": 11286,
    "mild": 4974,
    "severe": 287,
    "confirming": 621,
    "waiting": 270,
    "discharge": 3693,
    "death": 603
  }
```
The death is 603, and it's the `real-time` death number of `2020-05-07` (not the official one, the official number published by MHLW has about one day lagging.) the official calculate all number from `0:00 pm` to `11:59 am`, and the `real-time` one collected by me is calculate from `0:00 am` from `11:59 pm`. The real-time death number is collected in this file (https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/death.csv). The official one are here: https://github.com/swsoyee/2019-ncov-japan/tree/master/50_Data (`domesticDailyReport.csv`, `airportDailyReport.csv`, `flightDailyReport.csv` and `shipDailyReport.csv`). From April 22, MHLW also public the data under confirming (discharged number and death number), so I recorded them in `https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/confirmingData.csv`. The number in this file are number including the confirmed part and confirming part. But from May 8, MHLW have changed their structure of daily report, so these file are no longer update anymore. The new version are available here: https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/MHLW/summary.csv
(Maybe @ryo-ma also need to update the api.)

MHLW changed their standard or published some incomprehensible data sometime, so I suggest you better go to the website (https://covid-2019.live/en/) and see what I handle this data.

> 2 Total history's number of PCR on 2020-03-19 and 2020-03-25, Because the number of these two days is less than the previous two days.

Yes, it's *could* be negative in number of PCR :), the reason is: MHLW had found that some prefecture are counting their number of tests conducted not the number of tested people, so they subtract the number the other day.
You can refer to my site at `The situation in each prefecture > Multidimensional Comparison` and select the `Chiba`, and you will know that before `2020-03-24` the number of tested are `8676` and at `2020-03-25` the number was set to `31`.
Here is the official report link (Japanese) : https://www.mhlw.go.jp/stf/newpage_10442.html
And at the right of the first table, the number of tested people was `-918`.

**Comment by ryo-ma** [comment]
@swsoyee Thank you for the answer! And thank you for good product!
@a849173140 I probably think your questions are solved by his comment.

**Comment by a849173140** [comment]
@ryo-ma @swsoyee

**Comment by a849173140** [comment]
@ryo-ma @swsoyee 
Thank you very much for you help, I will check it.
@swsoyee I saw you Web site，very amazing! I'm working for a Janpan's COVID data visualization, learn a lot from your site. I don't know the application of R language on the website, so I can't study the code, but I have learned a lot from your analysis. Thank you!
