### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [ryo-ma/covid19-japan-web-api#32]
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/HZLABC

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ryo-ma** [comment]
@reeshmabijosh 
OK. I can do that. 
Why closed.

**Comment by k-goncharova** [comment]
Hello, thank you for your willingness to contribute. Seems like the issue was closed by mistake.  Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by ryo-ma** [comment]
I have signed up. How to take creator permissions?

**Comment by k-goncharova** [comment]
Permissions have been just given to you. Please let us know if you might need any help.
